name: '⚠️‼️ deploy_prod → rundgang-comingsoon-2024.rundgang.udk-berlin.de'

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:
    inputs:
      ref:
        description: The branch, tag or SHA to checkout
        required: true
        default: 'main'

jobs:
  deploy_dev:
    runs-on: ubuntu-latest

    env:
      ssh_user: 'root'
      ssh_host: 'rundgang-comingsoon-2024.rundgang.udk-berlin.de'
      ssh_key: ${{ secrets.SSH_RUNDGANG_UDK_BERLIN_DE }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.inputs.ref}}

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - run: npm clean-install
      - run: npm run build --if-present

      - run: mkdir -p ~/.ssh/
      - run: echo "$ssh_key" > ~/.ssh/private.key
      - run: chmod 600 ~/.ssh/private.key
      - run: |
          cat > ~/.ssh/config << EOF
          Host remote
            HostName $ssh_host
            User $ssh_user
            IdentityFile ~/.ssh/private.key
            StrictHostKeyChecking no
          EOF

      ## ssh access is restricted to `rrsync` via remote:~/.ssh/authorized_keys
      - name: Run rsync to securely copy the build directory to the remote host
        run: |
          rsync \
            --archive \
            --compress \
            --delete \
            --rsh="ssh -i ~/.ssh/private.key" \
            --progress \
            --verbose \
            out/ \
            remote:

